import jsPDF from 'jspdf';
import autoTable from 'jspdf-autotable';

export class PDFService {
    static generateProjectExecutiveSummary(project: any, metrics: any) {
        const doc = new jsPDF();

        // Header
        doc.setFontSize(22);
        doc.setTextColor(30, 41, 59);
        doc.text('EUSAI Executive Project Summary', 14, 22);

        doc.setFontSize(10);
        doc.setTextColor(148, 163, 184); // slate-400
        doc.text(`Generated on: ${new Date().toLocaleDateString()} ${new Date().toLocaleTimeString()}`, 14, 30);

        // Project Overview
        doc.setFontSize(14);
        doc.setTextColor(30, 41, 59);
        doc.text('1. Project Identity', 14, 45);

        autoTable(doc, {
            startY: 50,
            head: [['Field', 'Value']],
            body: [
                ['Project Name', project.name],
                ['Current Status', project.status],
                ['Baseline Budget', `$${Number(project.budget).toLocaleString()}`],
                ['Team Size', `${project.resources?.length || 0} Members`],
                ['Start Date', new Date(project.startDate).toLocaleDateString()],
            ],
            theme: 'striped',
            headStyles: { fillColor: [59, 130, 246] } // primary blue
        });

        // Health Metrics
        const currentY = (doc as any).lastAutoTable.finalY + 15;
        doc.text('2. Execution Health Metrics', 14, currentY);

        autoTable(doc, {
            startY: currentY + 5,
            head: [['Metric', 'Value', 'Status']],
            body: [
                ['Velocity', metrics.velocity || '85%', 'OPTIMAL'],
                ['Budget Burn Rate', metrics.budgetUsed || 'N/A', 'ON TRACK'],
                ['Tasks Remaining', metrics.tasksRemaining?.toString() || '12', 'MONITORED'],
                ['Resource Load', '92%', 'HIGH'],
            ],
            theme: 'grid',
            headStyles: { fillColor: [30, 41, 59] } // slate-800
        });

        // AI Assessment (Mocked for integration)
        const assessmentY = (doc as any).lastAutoTable.finalY + 15;
        doc.text('3. AI Assessment & Risk Analysis', 14, assessmentY);
        doc.setFontSize(10);
        doc.setTextColor(71, 85, 105); // slate-600
        const splitText = doc.splitTextToSize(
            "The EUSAI Intelligence Agent has analyzed current telemetry. Project is showing high execution velocity. Recommendation: Resource Alex Johnson is approaching burnout thresholds based on activity spikes in Mongo logs. Consider load balance redistribution in Sprint 4.",
            180
        );
        doc.text(splitText, 14, assessmentY + 10);

        // Footer branding
        const pageCount = (doc as any).internal.getNumberOfPages();
        for (let i = 1; i <= pageCount; i++) {
            doc.setPage(i);
            doc.setFontSize(8);
            doc.setTextColor(148, 163, 184);
            doc.text(`Page ${i} of ${pageCount} - Confidentially Generated by EUSAI BPM Intelligence Suite`, 14, 285);
        }

        doc.save(`${project.name.replace(/\s+/g, '_')}_Executive_Summary.pdf`);
    }
}
